### ISSUE TITLE
Mapbox vs leaflet?

### ISSUE THREAD

**Issue by sid-kap** [zoningspace/www.zoning.space#1]
Just curious, why did you guys choose to use Mapbox (as opposed to regular Leaflet)? It's really laggy (at least on my computer) even when just panning around the map, and especially when changing between styles. I don't think it's just your map, either—even in [their own example](https://www.mapbox.com/mapbox-gl-js/example/setstyle/) it takes almost 1 second to switch between styles.

**Comment by sid-kap** [comment]
@mattwigway

**Comment by mattwigway** [comment]
I chose mapbox because they're good at hosting and displaying large
datasets (the zoning dataset is almost 900mb). I think it's a little
sluggish due to dataset size, but I don't think leaflet would make it
better.

**Comment by sid-kap** [comment]
Ah, I didn't realize the dataset was that big. Makes sense!
